### ISSUE TITLE
Acceleration range

### ISSUE THREAD

**Issue by AmelMammar** [hhu-stups/abz2025_casestudy_autonomous_driving#13]
Page 2: from VEH6 and VEH7, acceleration should be in [−bmax, -bmin] \/[0, amax]. Am I wrong ?

**Comment by favu100** [comment]
There are edge cases where the acceleration could be in [-bmin,0] as well, e.g., when the difference between a full stop (0 m/s) and the current speed is less than bmin. 

Regarding the environment, one can also configure minimum target speeds, e.g., 10 m/s, 15 m/s etc. when decelerating. In those cases, the acceleration could also be in [-bmin,0] when the difference between the current speed and the target speed is less than bmin. However, this should not be relevant for the provided environments.

**Comment by leuschel** [comment]
The deceleration is between -bmax .. -bmin when executing the action "SLOWER" up until the point we reach the minimal speed, which in our document is 0 m/s. Once the we reach the minimal speed the deceleration is 0.

Fabian: in our document we do not talk about other target speeds; this will only confuse here.
